name: 'test my project'
on:
  - push
jobs:
  build:
    runs-on:  ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
    - name: npm install
      run: |
        make install
      env:
        CI: true
    - name: Run liner
      run: |
        make lint
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v3.0.0
      env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
          coverageCommand: make test-coverage
          debug: true